export const INCREASE_TOTAL = "INCREASE_TOTAL";
export const DECREASE_TOTAL = "DECREASE_TOTAL";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const CLEAR_TOTAL_PRICES = "CLEAR_TOTAL_PRICES";